# Common values for app1 between all environments
fullnameOverride: "app-01"
image:
  repository: nginx
  tag: latest
persistence:
  enabled: true
  storageClass: s3files-sc
  size: 1Gi
  mountPath: /usr/share/nginx/html