apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: nodeclass-system-patch.yml
    target:
      kind: NodeClass
      name: nodeclass-system

  - path: nodeclass-apps-patch.yml
    target:
      kind: NodeClass
      name: nodeclass-apps