apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: nodeclass-system
spec:
  role: iam-rol-auto-mode-eks-node-svc
  securityGroupSelectorTerms:
    # - tags:
    #     Name: secgrp-auto-mode-shared-node
    - id: sg-0c46c4ab208bfc0bf